# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0008_measurement_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensingnode',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Bus', verbose_name='bus where the node is coupled'),
        ),
    ]
