# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0011_auto_20170407_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensingNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Bus', verbose_name='bus where the node is coupled')),
            ],
        ),
    ]
