# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('light', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rain', models.DecimalField(decimal_places=1, max_digits=4)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Bus', verbose_name='bus that collected measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Stop', verbose_name='stop that received measurement'),
        ),
    ]
