# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20170117_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=-22.865635, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=-43.223648, max_digits=9),
            preserve_default=False,
        ),
    ]
