# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_auto_20170119_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensingNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Bus', verbose_name='bus where the node is coupled')),
            ],
        ),
        migrations.AlterField(
            model_name='measurement',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Bus', verbose_name='bus that collected measurement'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publisher.SensingNode', verbose_name='node that collected measurement'),
            preserve_default=False,
        ),
    ]
