# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0010_remove_measurement_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensingnode',
            name='bus',
        ),
        migrations.DeleteModel(
            name='SensingNode',
        ),
    ]
