# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0016_sensingnode_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='light',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='rain',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
